site_name: NoughtQ的笔记本
site_author: NoughtQ
site_url: 'https://notebook.noughtq.top'
site_description: NoughtQ的笔记本，主要记录一些 CS 相关的笔记

repo_url: https://github.com/noughtq/notebook
repo_name: NoughtQ/Notebook
use_directory_urls: false    # 加上这句后才能显示用 html img 相对路径插入的图片

copyright: Copyright &copy; 2024-2026 <a href="https://github.com/NoughtQ">NoughtQ</a>

theme:
  name: material
  language: zh
  favicon: assets/favicon.png
  custom_dir: overrides
  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.code.annotate
    - content.footnote.tooltips
    # - header.autohide
    - navigation.footer
    - navigation.indexes
    - navigation.path
    - navigation.prune
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.share
  font:
    text: JetBrains Mono, LXGW WenKai Screen GB Screen 
    code: JetBrains Mono, Consolas
  icon:
    repo: fontawesome/brands/git-alt
    logo: material/notebook-multiple
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  palette:
    - media: "(prefer-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Dark Mode
    - media: "(prefer-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Light Mode

hooks:
  - hooks/toc.py
  - hooks/tikzautomata.py
  # - hooks/tikzqtree.py


plugins:
  - blog:
      draft: false
  - changelog
  - drawio
  - glightbox
  - search
  - heti:
      disable_serve: true
  - statistics: # 需要在 markdown_extensions 里面加一句 md_in_html 才能显示 icon
      page_template: "assets/template.html"
      words_per_minute: 200
      page_check_metadata: counter
  - random_walk:
      black_list: ['index', 'changelog', 'links', 'board']
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
      enable_creation_date: true
      exclude:
        - index.md
        - changelog.md
        - links.md
      fallback_to_build_date: true
  # - termynal:
  #     prompt_literal_start:
  #       - "$"
  #       - ">"
  - encryptcontent:  
      # title_prefix: "🔒 "
      remember_password: True 
      summary: '看不到我~'
      decryption_failure_message: '密码错误'
      encryption_info_message: '应课程政策要求等原因，该笔记不对外公开，如有需要请联系我'
      button_class: 'md-search__icon'
      encrypted_something:
        mkdocs-encrypted-toc: [nav, class]
      password_file: 'passwords.yml'
      
  # - tikzautomata
  - rss:
      date_from_meta:
        as_creation: date.created
        as_update: date.updated
  - mkdocs-video:
      is_video: True


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
      - name: mermaid
        class: mermaid
        format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: ⚓︎
      title: 目录
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}} # enable Unicode link
  - md_in_html
  - footnotes
  - neoteroi.cards

extra:
  social:
    - icon: fontawesome/solid/home
      link: https://noughtq.top
    - icon: fontawesome/solid/blog
      link: https://blog.noughtq.top
    - icon: fontawesome/brands/github
      link: https://github.com/noughtq
    - icon: material/email
      link: mailto:noughtq666@gmail.com
  analytics:
    provider: google
    property: G-43NH8CVRCJ

extra_css:
  - css/card.css
  - css/custom.css
  - css/extra_changelog.css
  - css/header.css
  - css/sidebar.css
  - css/neoteroi-css.css
  - css/toc_extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
  # - https://fonts.googleapis.com/css2?family=JetBrains+Mono:ital,wght@0,100..800;1,100..800&display=swap
  - https://cdn.jsdelivr.net/npm/pseudocode@latest/build/pseudocode.min.css

extra_javascript:
  - js/anchor.js
  - js/katex.js
  - js/toc.js
  - js/typed.js
  - js/custom.js
  # - js/sidebar.js
  # - js/setting.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
  # - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/pseudocode@latest/build/pseudocode.min.js


nav: 
  - 🏫主页:
    - index.md
    - 🕑更新记录: changelog.md
    # - 🔗友链: links.md
    - 📋留言板: board.md

  - 🔡编程语言:
    - lang/index.md
    - C:
      - lang/c/index.md
    - C++:
      - lang/cpp/index.md
      - lang/cpp/1.md
      - lang/cpp/2.md
      - lang/cpp/3.md
      - lang/cpp/4.md
      - lang/cpp/5.md
      - lang/cpp/6.md
      - lang/cpp/7.md
      - lang/cpp/8.md
      - lang/cpp/9.md
      - lang/cpp/10.md
      - lang/cpp/11.md
      - lang/cpp/bagu.md
    - Python:
      - lang/py/index.md
      - 基础语法:
        - lang/py/dataStruct.md
        - lang/py/functObj.md
        - lang/py/classProtocol.md
        - lang/py/ctrlFlow.md
        - lang/py/metaProg.md
      - 标准库 & 第三方库:
        - lang/py/pyqt6.md
    - Java:
      - lang/java/index.md
      - lang/java/1.md
      - lang/java/2.md
      - lang/java/3.md
      - lang/java/4.md
    - x86 汇编语言:
      - lang/asm/index.md
      - lang/asm/1.md
      - lang/asm/2.md
      - lang/asm/3.md
      - lang/asm/4.md
      - lang/asm/5.md
    - 数据库语言:
      - SQLite: lang/sqlite.md
    
  - 📊数学相关:
    - math/index.md
    - 微积分（甲）:
      - math/calculus/index.md
      - math/calculus/7.md
      - math/calculus/8.md
      - math/calculus/9.md
      - math/calculus/10.md
      - math/calculus/11.md
      - math/calculus/appendix.md
    - math/linear-algebra.md
    - 离散数学及其应用:
      - math/dm/index.md
      - math/dm/1.md
      - math/dm/2.md
      - math/dm/3.md
      - math/dm/4.md
      - math/dm/5.md
      - math/dm/6.md
      - math/dm/8.md
      - math/dm/9.md
      - math/dm/10.md
      - math/dm/11.md
      - math/dm/Glossary.md
    - 概率论与数理统计:
      - math/pro-sta/index.md
      - math/pro-sta/1.md
      - math/pro-sta/2.md
      - math/pro-sta/3.md
      - math/pro-sta/4.md
      - math/pro-sta/5.md
      - math/pro-sta/6.md
      - math/pro-sta/7.md
      - math/pro-sta/8.md
      - math/pro-sta/exercises.md
    - 数值分析:
      - math/na/index.md
      - math/na/1.md
      - math/na/2.md
      - math/na/3.md
      - math/na/4.md
      - math/na/5.md
      - math/na/6.md
      - math/na/7.md
      - math/na/8.md
      - math/na/9.md
      - math/na/hw.md
      - math/na/quizzes.md
    - 计算理论:
      - math/toc/index.md
      - math/toc/1.md
      - math/toc/2.md
      - math/toc/3.md
      - math/toc/4.md
      - math/toc/5.md
    
  - 🧮算法相关:
    - algo/index.md
    - 数据结构基础:
      - algo/fds/index.md
      - algo/fds/2.md
      - algo/fds/3.md
      - algo/fds/4.md
      - algo/fds/5.md
      - algo/fds/6.md
      - algo/fds/7.md
      - algo/fds/8.md
      - algo/fds/9.md
      - Mistakes: algo/fds/mistakes.md
    - 高级数据结构与算法分析:
      - algo/ads/index.md
      - Balanced Search Trees:
        - algo/ads/1.md
        - algo/ads/2.md
      - Inverted Index: algo/ads/3.md
      - Heaps:
        - algo/ads/4.md
        - algo/ads/5.md
      - Algorithms:
        - algo/ads/6.md
        - algo/ads/7.md
        - algo/ads/8.md
        - algo/ads/9.md
        - algo/ads/10.md
        - algo/ads/11.md
        - algo/ads/12.md
        - algo/ads/13.md
        - algo/ads/14.md
        - algo/ads/15.md

  - 💾软件相关:
      - software/index.md
      - 图像信息处理:
        - software/dip/index.md
        - software/dip/1.md
        - software/dip/2.md
        - software/dip/3.md
        - software/dip/4.md
        - software/dip/5.md
        - software/dip/6.md
        - software/dip/7.md
        - software/dip/8.md
      - 软件工程:
        - software/se/index.md
      - 多媒体技术:
        - software/mt/index.md
      - 计算机图形学:
        - software/cg/index.md
        - software/cg/1.md
        - software/cg/2.md
        - software/cg/3.md
        - software/cg/4.md
        - software/cg/5.md
        - software/cg/6.md
        - software/cg/7.md
        - software/cg/8.md
        - software/cg/9.md
        - software/cg/10.md
        - software/cg/11.md
        - software/cg/12.md
      - 游戏引擎:
        - software/ge/index.md
        - software/ge/1.md
        - software/ge/2.md
        - software/ge/3.md
        - Rendering:
          - software/ge/4.md
          - software/ge/5.md
          - software/ge/6.md
          - software/ge/7.md
        - Animation:
          - software/ge/8.md
          - software/ge/9.md
        - Physics:
          - software/ge/10.md
          - software/ge/11.md
        - software/ge/12.md
        - Tool Chains:
          - software/ge/13.md
          - software/ge/14.md
        - Gameplay:
          - software/ge/15.md
          - software/ge/16.md
          - software/ge/17.md
        - Online Gaming:
          - Fundamentals: software/ge/18.md
          - Advanced Topics: software/ge/19.md

  - 💻系统相关:
    - sys/index.md
    - CSAPP:
      - sys/csapp/index.md
      - sys/csapp/1.md
      - sys/csapp/2.md
      - sys/csapp/3.md
      - sys/csapp/4.md
      - sys/csapp/5.md
      - sys/csapp/6.md
      - sys/csapp/7.md
      - sys/csapp/8.md
      - sys/csapp/9.md
      - sys/csapp/10.md
      - sys/csapp/11.md
      - sys/csapp/12.md
    - 数字逻辑设计:
      - sys/dld/index.md
      - sys/dld/1.md
      - sys/dld/2.md
      - sys/dld/3.md
      - sys/dld/4.md
      - sys/dld/5.md
      - sys/dld/6.md
      - sys/dld/7.md
      - sys/dld/verilog.md
    - 计算机组成:
      - sys/co/index.md
      - sys/co/1.md
      - sys/co/2.md
      - sys/co/3.md
      - sys/co/4.md
      - sys/co/5.md
      - sys/co/6.md
    - 计算机体系结构:
      - sys/ca/index.md
      - sys/ca/1.md
      - sys/ca/2.md
      - sys/ca/3.md
      - sys/ca/4.md
      - sys/ca/5.md
    - 数据库系统:
      - sys/db/index.md
      - sys/db/1.md
      - sys/db/2.md
      - sys/db/3.md
      - sys/db/4.md
      - sys/db/5.md
      - sys/db/6.md
      - sys/db/7.md
      - sys/db/8.md
      - sys/db/9.md
      - sys/db/10.md
      - sys/db/11.md
      - sys/db/12.md
      - sys/db/13.md
      - sys/db/14.md
      - sys/db/15.md
    - 操作系统:
      - sys/os/index.md
      - Overview:
        - sys/os/1.md
        - sys/os/2.md
      - Process Management:
        - sys/os/3.md
        - sys/os/4.md
        - sys/os/5.md
      - Process Synchronization:
        - sys/os/6.md
        - sys/os/7.md
        - sys/os/8.md
      - Memory Management:
        - sys/os/9.md
        - sys/os/10.md
      - Storage Management:
        - sys/os/11.md
        - sys/os/12.md
      - File System:
        - sys/os/13.md
        - sys/os/14.md
        - sys/os/15.md
    - 汇编与接口:
      - sys/aai/index.md
      - sys/aai/1.md
      - sys/aai/2.md
      - sys/aai/3.md
      - sys/aai/4.md
      - sys/aai/5.md
      - sys/aai/6.md
      - sys/aai/9.md
      - sys/aai/11.md
      - sys/aai/questions.md
    - 编译原理:
      - sys/poc/index.md

  - 🌏Web相关:
    - web/index.md
    - 计算机网络:
      - web/cn/index.md
      - web/cn/review.md
    - web/model.md
    - web/security.md
    - 前端:
      - web/frontend/index.md
      - web/frontend/html.md
      - web/frontend/css.md
      - JavaScript:
        - web/frontend/js/index.md
        - web/frontend/js/basic.md
        - web/frontend/js/browser.md
      - Vue.js:
        - web/frontend/vue/index.md
        - web/frontend/vue/basics.md
        - web/frontend/vue/component.md
        - web/frontend/vue/advanced.md 
    - 后端:
      - web/backend/index.md
      - Go:
        - web/backend/go/index.md
        - web/backend/go/basic.md
        - web/backend/go/cmd.md
        - web/backend/go/http.md
        - web/backend/go/logrus.md
        - web/backend/go/gorm.md
      - web/backend/database.md
    - 工具:
      - web/tools/index.md
      - web/tools/curl.md

  # - 🛡️信息安全:
  #   - CTF-101 短学期课程:
  #     - sec/ctf-101/index.md
  #     - Web:
  #       - sec/ctf-101/web/1.md
  #       - sec/ctf-101/web/2.md
  #     - Misc:
  #       - sec/ctf-101/misc/1.md
  #       - sec/ctf-101/misc/2.md

  - 🤖人工智能:
    - ai/index.md
    # - CS188 | Intro to AI:
    #   - ai/cs188/index.md
    #   - ai/cs188/intro.md
    #   - ai/cs188/search.md
    - 机器学习:
      - ai/ml/index.md
      - ai/ml/1.md
      - ai/ml/2.md
      - ai/ml/3.md
      - ai/ml/4.md
      - ai/ml/5.md
      - ai/ml/6.md
      - ai/ml/7.md
      - ai/ml/8.md
      - ai/ml/9.md
      - ai/ml/10.md
      - ai/ml/11.md
      - ai/ml/12.md
      - ai/ml/13.md
      - ai/ml/14.md
    - 生成式人工智能:
      - ai/genai/index.md
      - ai/genai/1.md
      - ai/genai/2.md
      - ai/genai/3.md
      - ai/genai/4.md
      - ai/genai/5.md
      - ai/genai/6.md
      - ai/genai/7.md
      - ai/genai/8.md
      - ai/genai/9.md
      - ai/genai/10.md
      - ai/genai/11.md
      - ai/genai/12.md
    - 计算机视觉:
      - ai/cv/index.md
      - ai/cv/1.md
      - Basics:
        - ai/cv/2.md
        - ai/cv/3.md
        - ai/cv/4.md
      - Reconstruction:
        - ai/cv/5.md
        - ai/cv/6.md
        - ai/cv/7.md
        - ai/cv/8.md
      - Deep Learning Basics:
        - 期末特供: ai/cv/dl.md
        - ai/cv/9.md
        - ai/cv/10.md
        - ai/cv/11.md
      - Perceiving and Understanding the Visual World:
        - ai/cv/12.md
        - ai/cv/13.md
        - ai/cv/14.md
        - ai/cv/15.md
        - ai/cv/16.md
        - ai/cv/17.md
        - ai/cv/18.md
        - ai/cv/19.md
        - ai/cv/20.md
        - ai/cv/21.md
        - ai/cv/22.md
        - ai/cv/23.md
        - ai/cv/24.md
    - 工具箱:
      - ai/toolbox/index.md
      - Numpy: ai/toolbox/numpy.md
      - PyTorch: ai/toolbox/torch.md
      - LangChain: ai/toolbox/langchain.md

  - 🗃️杂项:
    - misc/index.md
    - CS 相关:
      - 数据要素市场:
        - misc/dem/index.md
        - misc/dem/1.md
        - misc/dem/2.md
        - misc/dem/3.md
        - misc/dem/4.md
        - misc/dem/5.md
        - misc/dem/6.md
        - misc/dem/7.md
        - misc/dem/8.md
        - misc/dem/9.md
        - misc/dem/10.md
        - misc/dem/11.md
      - 量子计算理论基础与软件系统:
        - misc/qc/index.md
        - misc/qc/1.md
        - misc/qc/2.md
        - misc/qc/3.md
        - misc/qc/4.md
        - misc/qc/5.md
    - 心理学相关:
      - 心理学导论:
        - misc/psychology/intro/index.md
        - misc/psychology/intro/1.md
        - misc/psychology/intro/2.md
        - misc/psychology/intro/3.md
      - 社会心理学:
        - misc/psychology/social/index.md
        - misc/psychology/social/1.md
        - misc/psychology/social/2.md
    - 大学物理（乙）:
      - misc/physics/index.md
      - misc/physics/1.md
      - misc/physics/2.md
      - misc/physics/3.md
    - 创业启程: misc/entrepreneurship.md
   

  - 🛠️工具: 
    - tools/index.md
    - 实用工具: tools/practical-tools.md
    - Linux 基础:
      - tools/linux/index.md
      - tools/linux/shell.md
      - tools/linux/vim.md
    - Git: tools/git.md
    - 排版工具:
      - tools/typesetting/index.md
      - tools/typesetting/markdown.md
      - tools/typesetting/typst.md
      - tools/typesetting/latex.md

  - 📑论文阅读:
    - papers/index.md
    - 数据可视化:
      - papers/dv/index.md
      - papers/dv/nl4dv.md
      - papers/dv/viseval.md
      - papers/dv/matplotagent.md
